# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-28 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='refrence_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
