# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-02 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='refrence_image',
        ),
    ]
