# Generated by Django 2.0.6 on 2018-06-06 05:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180605_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='written_by',
            field=models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
    ]
