# Generated by Django 2.0.6 on 2018-06-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180606_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='written_by',
            field=models.CharField(max_length=50, verbose_name='auth.User'),
        ),
    ]
