# Generated by Django 2.0.6 on 2018-06-12 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20180606_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
