# Generated by Django 2.0.6 on 2018-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
