# Generated by Django 2.0.6 on 2018-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20180614_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlvote',
            field=models.IntegerField(default=0),
        ),
    ]
