# Generated by Django 2.0.6 on 2018-06-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20180615_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvote',
        ),
    ]
