# Generated by Django 2.0.6 on 2018-06-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_post_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlereview',
            name='vote',
        ),
    ]
