# Generated by Django 2.0.6 on 2018-06-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20180616_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='vote',
            new_name='post',
        ),
    ]
