# Generated by Django 2.0.6 on 2018-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180616_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(null=True, upload_to='pic/'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
